//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.01 at 08:56:37 PM SGT 
//


package trackPublisher;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TRACK_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRACK_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TRACK_NUMBER" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="LONGITUDE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="LATITUDE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="HEADING" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ALTITUDE" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="VELOCITY_X" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="VELOCITY_Y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="VELOCITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="UPDATE_TIME" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="URNO" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FLID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PREFFERED_CALLSIGN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DROPPED_TRACK" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tracktype",
    "trackid",
    "tracknumber",
    "longitude",
    "latitude",
    "heading",
    "altitude",
    "velocityx",
    "velocityy",
    "velocity",
    "updatetime",
    "urno",
    "flid",
    "prefferedcallsign",
    "droppedtrack"
})
@XmlRootElement(name = "TRACK")
public class TRACK {

    @XmlElement(name = "TRACK_TYPE", required = true)
    protected String tracktype;
    @XmlElement(name = "TRACK_ID")
    protected String trackid;
    @XmlElement(name = "TRACK_NUMBER", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger tracknumber;
    @XmlElement(name = "LONGITUDE")
    protected float longitude;
    @XmlElement(name = "LATITUDE")
    protected float latitude;
    @XmlElement(name = "HEADING")
    protected float heading;
    @XmlElement(name = "ALTITUDE")
    protected Float altitude;
    @XmlElement(name = "VELOCITY_X")
    protected float velocityx;
    @XmlElement(name = "VELOCITY_Y")
    protected float velocityy;
    @XmlElement(name = "VELOCITY")
    protected float velocity;
    @XmlElement(name = "UPDATE_TIME")
    protected long updatetime;
    @XmlElement(name = "URNO")
    protected Integer urno;
    @XmlElement(name = "FLID")
    protected String flid;
    @XmlElement(name = "PREFFERED_CALLSIGN")
    protected String prefferedcallsign;
    @XmlElement(name = "DROPPED_TRACK")
    protected boolean droppedtrack;

    /**
     * Gets the value of the tracktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRACKTYPE() {
        return tracktype;
    }

    /**
     * Sets the value of the tracktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRACKTYPE(String value) {
        this.tracktype = value;
    }

    /**
     * Gets the value of the trackid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRACKID() {
        return trackid;
    }

    /**
     * Sets the value of the trackid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRACKID(String value) {
        this.trackid = value;
    }

    /**
     * Gets the value of the tracknumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTRACKNUMBER() {
        return tracknumber;
    }

    /**
     * Sets the value of the tracknumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTRACKNUMBER(BigInteger value) {
        this.tracknumber = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public float getLONGITUDE() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLONGITUDE(float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public float getLATITUDE() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLATITUDE(float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     */
    public float getHEADING() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     */
    public void setHEADING(float value) {
        this.heading = value;
    }

    /**
     * Gets the value of the altitude property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getALTITUDE() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setALTITUDE(Float value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the velocityx property.
     * 
     */
    public float getVELOCITYX() {
        return velocityx;
    }

    /**
     * Sets the value of the velocityx property.
     * 
     */
    public void setVELOCITYX(float value) {
        this.velocityx = value;
    }

    /**
     * Gets the value of the velocityy property.
     * 
     */
    public float getVELOCITYY() {
        return velocityy;
    }

    /**
     * Sets the value of the velocityy property.
     * 
     */
    public void setVELOCITYY(float value) {
        this.velocityy = value;
    }

    /**
     * Gets the value of the velocity property.
     * 
     */
    public float getVELOCITY() {
        return velocity;
    }

    /**
     * Sets the value of the velocity property.
     * 
     */
    public void setVELOCITY(float value) {
        this.velocity = value;
    }

    /**
     * Gets the value of the updatetime property.
     * 
     */
    public long getUPDATETIME() {
        return updatetime;
    }

    /**
     * Sets the value of the updatetime property.
     * 
     */
    public void setUPDATETIME(long value) {
        this.updatetime = value;
    }

    /**
     * Gets the value of the urno property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getURNO() {
        return urno;
    }

    /**
     * Sets the value of the urno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setURNO(Integer value) {
        this.urno = value;
    }

    /**
     * Gets the value of the flid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLID() {
        return flid;
    }

    /**
     * Sets the value of the flid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLID(String value) {
        this.flid = value;
    }

    /**
     * Gets the value of the prefferedcallsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREFFEREDCALLSIGN() {
        return prefferedcallsign;
    }

    /**
     * Sets the value of the prefferedcallsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREFFEREDCALLSIGN(String value) {
        this.prefferedcallsign = value;
    }

    /**
     * Gets the value of the droppedtrack property.
     * 
     */
    public boolean isDROPPEDTRACK() {
        return droppedtrack;
    }

    /**
     * Sets the value of the droppedtrack property.
     * 
     */
    public void setDROPPEDTRACK(boolean value) {
        this.droppedtrack = value;
    }

}
